-- Chạy setup database — Oracle Free local (FREEPDB1, port 1522)
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON

CONNECT / AS SYSDBA
PROMPT === Bước 1: Tạo user APP_USER (nếu chưa có) ===
ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'APP_USER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER APP_USER IDENTIFIED BY "YOUR_PASSWORD"
      DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO APP_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO APP_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO APP_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO APP_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO APP_USER';
    DBMS_OUTPUT.PUT_LINE('Created APP_USER');
  ELSE
    DBMS_OUTPUT.PUT_LINE('APP_USER already exists — skip create');
  END IF;
END;
/

PROMPT === Bước 2: Tạo bảng (APP_USER) ===
CONNECT APP_USER/"YOUR_PASSWORD"@//localhost:1522/freepdb1

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'USERS';
  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Tables already exist. Drop manually if you need re-run.');
  END IF;
END;
/

@@001_create_tables.sql

PROMPT === Hoàn tất ===
SELECT table_name FROM user_tables ORDER BY table_name;

EXIT;
